"""Pilot 02 scene composition only; canonical effects remain in README.md."""
from urllib.parse import quote

def artwork(i):
    palettes=[('#e4d7b9','#a54b32','#303f39'),('#cddad5','#dcaa63','#25555a'),('#e5c5b2','#bf6049','#613d4a')]
    bg,sun,land=palettes[i]
    svg=f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 800 560"><rect width="800" height="560" fill="{bg}"/><circle cx="580" cy="145" r="72" fill="{sun}"/><path d="M0 420 210 110 445 420 620 245 800 380V560H0Z" fill="{land}"/><path d="m210 110-66 100 66-25 67 25Z" fill="#faf1dc"/><path d="M0 475Q200 410 400 485T800 475" fill="none" stroke="{sun}" stroke-width="22"/><path d="M55 40h95M55 40v95M745 520h-95M745 520v-95" fill="none" stroke="{land}" stroke-width="2"/></svg>'
    return 'data:image/svg+xml,'+quote(svg)

def head(kicker,title,copy):
    return f'<header><p class="scene-kicker">{kicker}</p><h1>{title}</h1><p>{copy}</p></header>'

HINTS={
'ds-111':'Scroll down to watch each metric fill. Values are always readable; reduced motion and unsupported browsers show the final fill.',
'ds-93':'Scroll sideways or Tab into the gallery and use arrow keys. Snap a new print to reveal its caption. Unsupported browsers show every caption.',
'ds-134':'Swipe a row left, scroll sideways, or Tab to its Open link. These links open local document summaries; nothing is deleted.',
'ds-30':'Read the guide, then follow the sticky checklist link. On short viewports the CTA returns to normal document flow.',
'ds-55':'Scroll slowly: each chapter pins near the top as the next covers it. Scroll back to revisit. Scale and dimming are progressive enhancements.',
'ds-69':'Tab into the table, then use left/right arrows, or scroll sideways. The first column stays pinned. Supporting browsers add a shadow away from the start.'}
HTML={}
HTML['111']='<article class="impact-report"><div class="report-intro">'+head('NORTH / Impact report · Q3 2026','Small steps.<br>Measurable change.','A quarterly snapshot of the systems that help our studio do better work.')+'<div class="report-total"><strong>216</strong><span>members completed onboarding<br>of 300 invited this quarter</span></div><a href="#metrics">Explore the quarter ↓</a><p class="report-cue">SCROLL TO REVEAL / 03 METRICS</p></div><section id="metrics" aria-label="Quarterly metrics">'+''.join(f'<div class="kpi" style="--kpi:{value}%"><p class="scene-kicker">0{i+1} / {label}</p><h2>{value}%</h2><p>{copy}</p><div class="kpi-track" aria-hidden="true"><i></i></div><small>{detail}</small></div>' for i,(label,value,copy,detail) in enumerate([('Activation',72,'A confident first week.','216 of 300 members completed onboarding'),('Retention',94,'Good habits that stick.','188 of 200 members returned this month'),('Delivery',86,'Promises, kept.','43 of 50 milestones delivered on time')]))+'</section><footer class="report-tail"><h2>Progress, not perfection.</h2><p>Illustrative studio data. Every percentage has a denominator.</p><a href="#metrics">Read the metrics again ↑</a></footer></article>'
HTML['93']='<article class="field-gallery">'+head('FIELD EDITIONS / Original vector landscapes','A place to pause.','Three imagined landscapes, printed in the colours of a slower season.')+'<div class="snap-carousel" tabindex="0" role="region" aria-label="Three landscape prints">'+''.join(f'<figure class="slide"><img src="{artwork(i)}" alt="{alt}"><figcaption class="caption">0{i+1} / {name}</figcaption></figure>' for i,(name,alt) in enumerate([('The high pass','Rust sun above a dark alpine ridge'),('Northern light','Golden sun above teal mountains'),('Evening tide','Rose hills beneath a terracotta sun')]))+'</div><div class="gallery-index"><span>LANDSCAPE SERIES / 001—003</span><span>Explore →</span></div></article>'
names=['Field notes','Studio agreement','September invoice']
HTML['134']='<article class="document-inbox">'+head('PAPERTRAIL / Shared workspace','Your reading room.','Three documents ready for a closer look. Reveal a row’s Open link, or reach it directly with Tab.')+'<p class="inbox-label">RECENT DOCUMENTS <span>03</span></p><ul class="swipe-list">'+''.join(f'<li class="swipe-item" tabindex="0" aria-label="{name}; scroll right or Tab to open"><div class="swipe-content"><span class="file-mark">0{i+1}</span><div><strong>{name}</strong><small>PDF · {i+2} pages · 26 Sep 2026</small></div><span aria-hidden="true">←</span></div><a class="swipe-action" href="#doc-{i}">Open<span class="sr-only"> {name}</span></a></li>' for i,name in enumerate(names))+'</ul><p class="inbox-note">← Swipe left to reveal · No destructive actions</p><div class="document-summaries">'+''.join(f'<section id="doc-{i}" tabindex="-1"><p class="scene-kicker">Document 0{i+1} / Summary</p><h2>{name}</h2><p>{copy}</p><a href="#inbox-top">Back to documents ↑</a></section>' for i,(name,copy) in enumerate(zip(names,['Site observations from our September workshop. Review the material samples before the next studio meeting.','A plain-language outline of scope, review rounds and delivery dates. For demonstration only; not a signed agreement.','A sample record of the month’s studio services. No payment is requested or processed.'])))+'</div></article>'
HTML['134']='<div id="inbox-top">'+HTML['134']+'</div>'
chapters=[('Start with what matters.','Choose one project you can finish, not five you can only start. Write down the change you want someone to feel when the work is done. That sentence will guide every decision that follows.','Define a useful outcome'),('Make room for the work.','Protect a quiet hour. Gather your references, close the extra tabs, and place the tools you need within reach. A thoughtful environment is not a luxury; it makes your next action easier.','Prepare your workspace'),('Leave a clear handover.','A finished file is only part of the work. Explain what changed, what remains open, and where the next person should begin. Kind documentation lets good work keep moving.','Share context, not just files')]
HTML['30']='<article class="studio-guide">'+head('THE STUDIO HANDBOOK / 7 minute read','A better beginning.','A practical guide to starting creative work with clarity, care and enough room to think.')+'<div class="guide-body">'+''.join(f'<section><span class="chapter-number">0{i+1}</span><h2>{title}</h2><p>{copy}</p><aside>FIELD NOTE / {note}</aside><p>Try it today: leave yourself a short note about the next concrete step. Return to that note before opening your tools tomorrow.</p></section>' for i,(title,copy,note) in enumerate(chapters))+'</div><nav class="sticky-cta" aria-label="Reading next step"><span>Ready when you are.<small>A three-point starting checklist</small></span><a href="#checklist">Open checklist ↗</a></nav></article><section id="checklist" class="guide-checklist" tabindex="-1"><p class="scene-kicker">YOUR NEXT STEP</p><h2>Make a little room.</h2>'+''.join(f'<label><input type="checkbox"> {x}</label>' for x in ['Name the outcome','Protect a quiet hour','Write the handover note'])+'<p>Local checklist only. Nothing is saved or sent.</p></section>'
HTML['55']='<article class="expedition">'+head('THE LONG WAY / Three field notes','Go slowly.<br>Notice more.','A small guide to travelling with attention. Scroll to stack the chapters; reverse your journey to uncover them.')+'<p class="deck-cue">↓ THREE CHAPTERS, ONE CONTINUOUS JOURNEY</p><div class="card-stack">'+''.join(f'<article class="card"><div class="deck-copy"><p class="scene-kicker">CHAPTER 0{i+1} / {tag}</p><h2>{title}</h2><p>{copy}</p><span>FIELD GUIDE — 2026</span></div><img src="{artwork(i)}" alt="Illustrated mountain landscape"></article>' for i,(tag,title,copy) in enumerate([('Departure','Take the quiet route.','Leave the main road. Walk at a pace that lets you hear the landscape change.'),('Attention','Stay a little longer.','The first view is only the beginning. Sit down, look again, and let the small details arrive.'),('Return','Bring less. Remember more.','Keep a few notes, a sketch, a story. Leave the place as generous as you found it.')]))+'</div><footer class="deck-end"><h2>The journey stays with you.</h2><p>Scroll back to uncover the chapters.</p></footer></article>'
rows=[('Alder Studio','Design','24','EU West','Mira Chen','04 Nov 2026','Active'),('North House','Editorial','12','US East','Sam Rivera','12 Nov 2026','Active'),('Common Ground','Research','36','EU North','Iris Wells','18 Nov 2026','Review'),('Fieldwork Co.','Strategy','18','AP South','Noah Park','22 Nov 2026','Active'),('Still Office','Design','8','EU West','Ada Reed','01 Dec 2026','Active'),('Open Form','Editorial','16','US West','Leo Bell','08 Dec 2026','Review'),('Morrow Lab','Research','42','EU North','Kai Moore','14 Dec 2026','Active'),('Good Measure','Strategy','10','AP East','Eva Lane','21 Dec 2026','Active')]
HTML['69']='<article class="accounts-report">'+head('ORBIT / Workspace operations','Good company.','Eight teams, one shared view. Compare the details without losing track of who you’re looking at.')+'<div class="table-summary"><strong>8 <small>workspaces</small></strong><strong>166 <small>total seats</small></strong><span>Renewals / Nov—Dec 2026</span></div><div class="table-wrapper" tabindex="0" role="region" aria-label="Workspace renewals; scroll horizontally"><table><caption>Workspace renewals · illustrative data</caption><thead><tr>'+''.join(f'<th scope="col">{x}</th>' for x in ['Workspace','Team','Seats','Region','Owner','Renewal','Status'])+'</tr></thead><tbody>'+''.join('<tr><th scope="row">'+r[0]+'</th>'+''.join(f'<td>{x}</td>' for x in r[1:])+'</tr>' for r in rows)+'</tbody></table></div><p class="table-foot">PINNED: WORKSPACE <span>Scroll for renewal details →</span></p></article>'
CSS={}
BASE='''
html:has(.showcase) {scroll-behavior:auto}
.showcase {width:min(100%,960px)}
.showcase header>p:last-child {max-width:52ch;color:var(--color-text-muted)}
.showcase .sr-only {position:absolute;width:1px;height:1px;overflow:hidden;clip-path:inset(50%)}
.showcase :target {scroll-margin-block:24px}
'''
CSS['ds-111']=BASE+'''
.impact-report {--color-primary:light-dark(#176554,#85d9b9)}
.report-intro {min-height:100dvh;padding-top:8vh;display:flex;flex-direction:column;align-items:start}
.report-intro h1 {font-size:clamp(46px,6vw,84px)}
.report-total {display:flex;align-items:center;gap:24px;border-top:1px solid var(--color-border);padding:28px 0;margin-top:24px;flex-wrap:wrap}.report-total strong {font-size:90px;letter-spacing:-.08em;line-height:1}.report-total span {font-size:14px}
.report-intro .report-cue {margin-top:auto;padding-block:44px;font:11px ui-monospace,monospace;letter-spacing:.12em}
.impact-report #metrics {max-width:740px;margin:auto}.impact-report .kpi {padding:42px 0 64px;border-top:1px solid var(--color-border);min-height:330px}.impact-report .kpi h2 {font-size:72px;letter-spacing:-.06em;margin:18px 0;line-height:1}.impact-report .kpi small {display:block;margin-top:16px}.report-tail {padding-block:100px;min-height:75vh}
'''
CSS['ds-93']=BASE+'''
.field-gallery {padding-block:28px}.field-gallery header {margin-bottom:32px}.field-gallery .slide img {aspect-ratio:10/7;object-fit:cover}.field-gallery .caption {max-width:calc(100% - 24px);font:16px/1.4 Georgia,serif;border-radius:4px;padding:12px 18px}.gallery-index {display:flex;justify-content:space-between;gap:20px;margin-top:20px;font:11px ui-monospace,monospace}.field-gallery .snap-carousel {padding-bottom:12px}
'''
CSS['ds-134']=BASE+'''
.showcase:has(.document-inbox) {max-width:660px}.document-inbox {border:1px solid var(--color-border);background:var(--color-surface);padding:clamp(18px,4vw,40px)}.document-inbox h1 {font-size:clamp(34px,4vw,48px)}.inbox-label {font:11px ui-monospace,monospace;display:flex;justify-content:space-between;border-bottom:1px solid var(--color-border);padding-block:24px 12px}.swipe-content {display:flex;align-items:center;gap:16px;border-bottom:1px solid var(--color-border)}.swipe-content>div {flex:1;min-width:0}.swipe-content strong {font-size:15px}.swipe-content small {display:block;color:var(--color-text-muted);margin-top:4px}.file-mark {font:18px Georgia,serif;color:var(--color-text-muted)}.inbox-note {font-size:12px;padding-top:18px}.document-summaries {margin-top:60px}.document-summaries section {padding-block:28px;border-top:1px solid var(--color-border)}.document-summaries section:target {outline:2px solid var(--color-primary);outline-offset:8px}
'''
CSS['ds-30']=BASE+'''
.showcase:has(.studio-guide) {max-width:780px}.studio-guide>header {padding-block:30px 50px;border-bottom:1px solid var(--color-border)}.studio-guide h1 {font-size:clamp(48px,6vw,76px)}.guide-body {padding-bottom:120px}.guide-body section {padding:50px 0;max-width:60ch;min-height:62vh;scroll-margin-bottom:140px}.chapter-number {font:56px Georgia,serif;color:var(--color-text-muted)}.guide-body h2 {font:36px Georgia,serif}.guide-body p {font-size:18px;line-height:1.9}.guide-body aside {border-left:3px solid var(--color-primary);padding:20px;font:12px ui-monospace,monospace;margin:30px 0;background:var(--color-surface-offset)}.sticky-cta {padding:16px 20px;display:flex;align-items:center;justify-content:space-between;gap:12px;flex-wrap:wrap}.sticky-cta span {font-weight:600}.sticky-cta small {display:block;font-weight:400}.sticky-cta a {background:var(--color-primary);color:var(--color-bg);padding:8px 18px;border-radius:4px}.guide-checklist {padding-block:100px;min-height:75vh}.guide-checklist label {display:flex;gap:14px;align-items:center;min-height:56px;border-bottom:1px solid var(--color-border)}.guide-checklist p:last-child {margin-top:28px;font-size:13px}
'''
CSS['ds-55']=BASE+'''
.expedition>header {padding-block:40px 80px}.expedition h1 {font-size:clamp(50px,6vw,80px)}.deck-cue {font:11px ui-monospace,monospace;letter-spacing:.1em;padding-bottom:28px}.expedition .card-stack {gap:20vh;padding-bottom:35vh}.expedition .card {display:grid;grid-template-columns:1fr 1fr;min-height:480px;background:#e4d7b9;color:#303f39;border:1px solid #303f3933;border-radius:12px;overflow:hidden;box-shadow:0 12px 30px #0002}.expedition .card:nth-child(2) {background:#cddad5;color:#25555a}.expedition .card:nth-child(3) {background:#e5c5b2;color:#613d4a}.deck-copy {padding:clamp(24px,4vw,48px);display:flex;flex-direction:column;align-items:start}.deck-copy h2 {font:clamp(30px,4vw,48px)/1.05 Georgia,serif}.deck-copy>span {font:10px ui-monospace,monospace;margin-top:auto}.expedition .card img {width:100%;height:100%;object-fit:cover;min-width:0}.deck-end {min-height:60vh;padding-top:60px}@media(max-width:600px) {.expedition .card {grid-template-columns:1fr;min-height:0}.expedition .card img {height:160px}.deck-copy {min-height:300px}.deck-copy h2 {margin-block:20px}}@media(max-height:550px) {.expedition .card {position:static}}
'''
CSS['ds-69']=BASE+'''
.accounts-report {padding-block:24px}.table-summary {display:flex;gap:32px;align-items:center;flex-wrap:wrap;padding-block:24px;margin-block:24px;border-block:1px solid var(--color-border)}.table-summary strong {font-size:32px;letter-spacing:-.03em}.table-summary small {display:block;font-size:11px;font-weight:400;letter-spacing:0;text-transform:uppercase}.table-summary>span {margin-left:auto;font-size:12px}.accounts-report table {border-collapse:separate;border-spacing:0;min-width:1080px;width:100%;font-size:14px}.accounts-report caption {text-align:left;padding:0 0 20px;font-size:12px}.accounts-report th,.accounts-report td {text-align:left;white-space:nowrap;padding:18px 22px;border-bottom:1px solid var(--color-border)}.accounts-report thead th {font:11px ui-monospace,monospace;text-transform:uppercase}.accounts-report th:first-child {min-width:190px;z-index:1}.table-foot {display:flex;justify-content:space-between;flex-wrap:wrap;gap:12px;font:11px ui-monospace,monospace;margin-top:20px!important}
'''
