"""Pilot 06 product scenes: content, layout and art direction only.

Overlay positioning, dismissal, focus affordances and motion live in README.md.
Every scene destination is an actual fragment in this standalone document.
"""

HINTS = {
    'ds-97': 'Open Explore. Use the links to travel within this guide. Close with the button or Escape; backdrop dismissal depends on closedby support.',
    'ds-117': 'Read the brief goes to the brief. The adjacent arrow opens a separate native project index; Escape or click elsewhere to dismiss it.',
    'ds-131': 'Preview a notice, then use Close to dismiss it. This manual notification will not time out or close on Escape or an outside click.',
}

HTML = {
    '97': '''<div class="nav-site" id="nav-home">
<header class="nav-site__header"><div class="nl-brand"><span class="nl-symbol" aria-hidden="true">N<span>·</span></span><span>NORTHLINE<br><small>FIELD GUIDE</small></span></div><span class="nl-edition">INDEPENDENT ROUTES · ISSUE 04</span><button type="button" class="nav-open" commandfor="site-drawer" command="show-modal">Explore <span aria-hidden="true">☰</span></button></header>
<main><div class="nl-hero"><div><p class="nav-site__eyebrow">A guide to going slowly / 2026</p><h1>Go somewhere<br><em>quieter.</em></h1><p class="nl-lede">Paths worth taking, places worth lingering, and a little room to get lost along the way.</p><a class="nl-inline" href="#nav-routes">Discover the routes <span aria-hidden="true">↗</span></a></div><div class="nl-landscape" aria-hidden="true"><div class="nl-sun"></div><div class="nl-hill nl-hill--back"></div><div class="nl-hill nl-hill--front"></div><span>52° 14′ N<br>03° 04′ W</span></div></div>
<div class="nl-caption"><span>04 / A DIFFERENT PACE</span><span>SCROLL TO EXPLORE ↓</span></div>
<div class="nl-sections"><section id="nav-routes"><span>01 / WHERE TO GO</span><h2>Routes for the unhurried.</h2><p>Follow an old railway trail through the pines, or take the river path into town. Both are better without a schedule.</p></section><section id="nav-notes"><span>02 / WHAT TO NOTICE</span><h2>Field notes.</h2><p>Look for the light in the canopy, the quiet of a side street, and the places you almost walked past.</p></section><section id="nav-visit"><span>03 / BEFORE YOU LEAVE</span><h2>Plan a visit.</h2><p>Comfortable shoes. A paper map. Enough time to take the longer route home.</p></section></div></main></div>
<dialog id="site-drawer" class="nav-drawer" closedby="any" aria-labelledby="drawer-title"><div class="nav-drawer__head"><span class="nl-drawer-brand">NORTHLINE <small> / 04</small></span><form method="dialog"><button type="submit" value="close" class="nav-close">Close <span aria-hidden="true">×</span></button></form></div><p class="nav-drawer__label" id="drawer-title">THE FIELD GUIDE / EXPLORE</p><nav aria-label="Guide sections"><a href="#nav-home"><span>01</span> Home <b aria-hidden="true">↗</b></a><a href="#nav-routes"><span>02</span> Routes <b aria-hidden="true">↗</b></a><a href="#nav-notes"><span>03</span> Field notes <b aria-hidden="true">↗</b></a><a href="#nav-visit"><span>04</span> Plan a visit <b aria-hidden="true">↗</b></a></nav><p class="nav-drawer__foot">Choose a section, then Close to view it.<br><small>Independent routes for curious people.</small></p></dialog>''',
    '117': '''<main class="split-page"><header class="sp-header"><strong>atelier<span> / </span>index</strong><span>PROJECT SPACE &nbsp;·&nbsp; 2026</span></header><div class="sp-body"><div class="sp-overview"><p class="sp-kicker">01 / ACTIVE PROJECT</p><h1>The Orchard<br><em>identity.</em></h1><p class="sp-lede">A warm, adaptable visual language for a neighbourhood market finding its place in the city.</p><div class="sp-meta"><span>CLIENT<br><strong>The Orchard</strong></span><span>DISCIPLINE<br><strong>Identity & signage</strong></span><span>STATUS<br><strong>In progress</strong></span></div><div class="sp-controls"><span class="sp-action-label">EXPLORE THIS PROJECT</span><div class="split"><a class="split-main" href="#project-brief">Read the brief <span aria-hidden="true">↗</span></a><button type="button" class="split-more" commandfor="split-menu" command="toggle-popover" aria-label="More project links"><span aria-hidden="true">⌄</span></button></div></div></div><div class="sp-art" aria-hidden="true"><span class="sp-art-caption">THE ORCHARD<br><small>EVERYDAY, FRESH.</small></span><div class="sp-orb sp-orb-one"></div><div class="sp-orb sp-orb-two"></div><span class="sp-art-foot">GATHER GOOD THINGS. &nbsp; ◇ &nbsp; 2026</span></div></div><div class="sp-sections"><section id="project-brief"><span>01 / BRIEF</span><h2>A market for everyone.</h2><p>Identity, signage and a reusable seasonal palette. The system has to feel familiar on a paper bag and unmistakable from across the street.</p></section><section id="project-timeline"><span>02 / TIMELINE</span><h2>From first sketch to street.</h2><p>Discovery in September; first concepts in October; a neighbourhood launch when the signs are ready.</p></section><section id="project-people"><span>03 / PEOPLE</span><h2>Made together.</h2><p>A small team of designers and market organisers shaping something that belongs to the block.</p></section></div></main><div id="split-menu" popover="auto" class="split-menu" aria-label="More project links"><p>PROJECT INDEX / 02–03</p><a href="#project-timeline">View timeline <span aria-hidden="true">↗</span></a><a href="#project-people">Meet the team <span aria-hidden="true">↗</span></a></div>''',
    '131': '''<main class="toast-page"><header class="tp-header"><strong>PAPERTRAIL<span> / READING DESK</span></strong><span>ISSUE 012 &nbsp; · &nbsp; AUTUMN 2026</span></header><div class="tp-layout"><div class="tp-essay"><p class="tp-kicker">A NOTE ON ATTENTION &nbsp; / &nbsp; 4 MIN READ</p><h1>Keep the good<br>ideas <em>close.</em></h1><p class="tp-lede">The best ideas often arrive quietly. A margin note, a turn of phrase, something you almost missed.</p><p>Make a little space for them. And when you are ready, go back to reading. This is a local demonstration — no notes are saved here.</p><button type="button" class="toast-trigger" commandfor="auto-toast-1" command="show-popover">Preview a notice <span aria-hidden="true">↗</span></button><p class="tp-under">PREVIEW ONLY / NO DATA IS STORED</p></div><aside class="tp-card" aria-label="Reading selection"><div class="tp-card-art" aria-hidden="true"><div class="tp-page"></div><div class="tp-pencil"></div></div><span>ON YOUR DESK / 01</span><h2>On noticing<br>the details.</h2><p>An invitation to read a little more slowly.</p></aside></div><footer>THE READING DESK &nbsp; / &nbsp; SMALL THINGS, WELL KEPT.</footer></main><div id="auto-toast-1" popover="manual" class="auto-toast" aria-label="Preview notice"><span class="auto-toast__mark" aria-hidden="true">i</span><span role="status"><strong>Just a preview</strong><br>No notes were saved.</span><button type="button" class="auto-toast__close" commandfor="auto-toast-1" command="hide-popover" aria-label="Dismiss notice">Close <span aria-hidden="true">×</span></button></div>''',
}

CSS = {
    'ds-97': '''
/* The generic demo page enables smooth fragment scrolling. A modal navigation
   destination must settle before the visitor dismisses the drawer. */
html:has(.nav-site){scroll-behavior:auto}
.showcase:has(.nav-site){max-width:1120px;--color-primary:light-dark(#233a32,#b7d4bd);--color-text:light-dark(#22362f,#e7efe6);--color-bg:light-dark(#f6f3e9,#192821);--color-border:light-dark(#d2d8ca,#4d5f51);--color-surface-offset:light-dark(#e9e9dc,#34463a);--color-accent:light-dark(#94652d,#ebbd78)}
.nav-site{width:100%;border:1px solid var(--color-border);border-radius:18px;overflow:hidden;background:var(--color-bg)}
.nav-site__header{padding:14px clamp(20px,4vw,48px);border-bottom:1px solid var(--color-border)}
.nl-brand{display:flex;gap:12px;align-items:center;font-size:13px;font-weight:800;line-height:1.1;letter-spacing:.12em}.nl-brand small{font-size:9px;letter-spacing:.2em}.nl-symbol{width:42px;height:42px;border-radius:50%;display:grid;place-items:center;background:var(--color-primary);color:var(--color-bg);font:italic 28px Georgia,serif}.nl-symbol span{position:absolute;transform:translate(14px,-8px);font:20px Georgia,serif}.nl-edition,.nl-caption,.nav-site__eyebrow,.nav-drawer__label,.nl-sections section>span{font:600 11px/1.4 ui-monospace,monospace;letter-spacing:.12em;color:var(--color-text-muted)}
.nav-open,.nav-close{background:transparent;border:1px solid var(--color-border);border-radius:100px;color:inherit}.nav-open span,.nav-close span{margin-left:10px}.nav-open:hover,.nav-close:hover{background:var(--color-surface-offset)}
.nl-hero{display:grid;grid-template-columns:1.1fr .9fr;min-height:430px}.nl-hero>div:first-child{padding:clamp(32px,5vw,70px) clamp(24px,5vw,62px)}.nl-hero h1{font-size:clamp(44px,5.5vw,74px);line-height:1;margin:20px 0}.nl-hero h1 em{font-weight:400;color:light-dark(#718d6c,#b7d4bd)}.nl-lede{max-width:40ch;font-size:17px;line-height:1.65;color:var(--color-text-muted)}.nl-inline{display:inline-flex;padding:10px 0;border-bottom:1px solid currentColor;text-decoration:none;font-size:14px;font-weight:600;gap:20px}
.nl-landscape{position:relative;overflow:hidden;min-height:330px;background:light-dark(#e0dfcc,#304536)}.nl-sun{position:absolute;width:130px;aspect-ratio:1;border-radius:50%;background:light-dark(#eac28b,#d9ae78);top:15%;left:28%}.nl-hill{position:absolute;border-radius:50% 50% 0 0}.nl-hill--back{width:130%;height:64%;bottom:-23%;left:-36%;transform:rotate(-17deg);background:light-dark(#9caf91,#799473)}.nl-hill--front{width:140%;height:70%;bottom:-40%;left:15%;transform:rotate(12deg);background:light-dark(#3b5b47,#172f27)}.nl-landscape>span{position:absolute;bottom:20px;right:22px;text-align:right;color:#f7efe0;font:11px/1.5 ui-monospace,monospace}
.nl-caption{display:flex;justify-content:space-between;gap:12px;padding:16px clamp(24px,5vw,62px);border-top:1px solid var(--color-border)}.nl-sections{display:grid;grid-template-columns:repeat(3,1fr);border-top:1px solid var(--color-border)}.nl-sections section{padding:28px;border-right:1px solid var(--color-border);scroll-margin-top:12px}.nl-sections section:last-child{border:0}.nl-sections h2{font:normal 24px Georgia,serif;margin:12px 0}.nl-sections p{font-size:14px;color:var(--color-text-muted);margin:0}
.nav-drawer{background:light-dark(#f6f3e9,#192821);color:light-dark(#22362f,#e7efe6);border-right:1px solid light-dark(#d2d8ca,#4d5f51);--color-border:light-dark(#d2d8ca,#4d5f51);--color-surface-offset:light-dark(#e9e9dc,#34463a);--color-accent:light-dark(#94652d,#ebbd78)}
.nl-drawer-brand{font-weight:800;letter-spacing:.13em;font-size:13px}.nl-drawer-brand small{font-size:11px;font-weight:400}.nav-drawer__label{color:light-dark(#758071,#abb9a8)}.nav-drawer nav a{font:normal 26px Georgia,serif}.nav-drawer nav a span{font:11px ui-monospace,monospace;color:light-dark(#738472,#acc3aa)}.nav-drawer nav a b{margin-left:auto;font:16px system-ui}.nav-drawer__foot{font:italic 22px/1.4 Georgia,serif}.nav-drawer__foot small{font:12px system-ui;color:light-dark(#68776d,#aec0ae)}
@media(max-width:700px){.nl-edition{display:none}.nl-hero{grid-template-columns:1fr}.nl-hero>div:first-child{padding:34px 26px}.nl-landscape{min-height:210px}.nl-sections{grid-template-columns:1fr}.nl-sections section{border-right:0;border-bottom:1px solid var(--color-border)}}
''',
    'ds-117': '''
.showcase:has(.split-page){max-width:1100px;--color-primary:light-dark(#62352b,#edbb98);--color-text:light-dark(#322c26,#f0e9df);--color-bg:light-dark(#faf6ec,#211d1b);--color-border:light-dark(#dbcabb,#514137);--color-surface-offset:light-dark(#efe2d3,#43352e);--color-accent:light-dark(#823e33,#f5bd9b)}
.split-page{width:100%;background:var(--color-bg);color:var(--color-text);border:1px solid var(--color-border);border-radius:16px;overflow:hidden}.sp-header{padding:22px clamp(22px,4vw,48px);display:flex;justify-content:space-between;align-items:center;gap:12px;border-bottom:1px solid var(--color-border)}.sp-header strong{font-size:22px;letter-spacing:-.08em}.sp-header strong span{color:var(--color-primary)}.sp-header>span,.sp-kicker,.sp-action-label,.sp-sections section>span{font:600 11px ui-monospace,monospace;letter-spacing:.12em;color:var(--color-text-muted)}.sp-body{display:grid;grid-template-columns:1.1fr .9fr;min-height:490px}.sp-overview{padding:clamp(28px,4vw,55px)}.sp-overview h1{font-size:clamp(46px,5vw,72px);line-height:1;margin:22px 0}.sp-overview h1 em{color:var(--color-primary);font-weight:normal}.sp-lede{font-size:17px;max-width:42ch;color:var(--color-text-muted)}.sp-meta{display:flex;gap:clamp(14px,3vw,32px);flex-wrap:wrap;padding:20px 0;border-block:1px solid var(--color-border);margin:26px 0;font:10px/1.8 ui-monospace,monospace;letter-spacing:.08em;color:var(--color-text-muted)}.sp-meta strong{font:600 13px system-ui;color:var(--color-text)}.sp-controls{display:flex;align-items:center;gap:16px;flex-wrap:wrap}.split-main,.split-more{background:light-dark(#62352b,#edbb98);color:light-dark(#fffaf0,#211d1b);font-weight:600}.split-more span{font-size:23px;line-height:1;transform:translateY(-4px)}.split-more:active,.split-main:active{filter:brightness(.85)}
.sp-art{position:relative;overflow:hidden;background:light-dark(#dec2a2,#6d493e);display:flex;align-items:flex-start;padding:clamp(28px,4vw,50px)}.sp-art-caption{z-index:1;font:600 clamp(32px,4vw,56px)/.98 Georgia,serif;color:#412f26;letter-spacing:-.06em}.sp-art-caption small{font:600 11px ui-monospace,monospace;letter-spacing:.2em}.sp-orb{position:absolute;border-radius:50%;box-shadow:inset -25px -28px 55px #37282035,18px 25px 45px #3c261b3d}.sp-orb-one{width:52%;aspect-ratio:1;right:13%;top:29%;background:#d16842}.sp-orb-two{width:34%;aspect-ratio:1;left:12%;bottom:-5%;background:#8e9c59}.sp-art-foot{position:absolute;right:25px;bottom:22px;font:10px ui-monospace,monospace;color:#412f26}.sp-sections{display:grid;grid-template-columns:repeat(3,1fr);border-top:1px solid var(--color-border)}.sp-sections section{padding:28px;border-right:1px solid var(--color-border);scroll-margin-top:12px}.sp-sections section:last-child{border:0}.sp-sections h2{font:normal 24px Georgia,serif;margin:12px 0}.sp-sections p{font-size:14px;color:var(--color-text-muted);margin:0}
.split-menu{background:light-dark(#faf6ec,#211d1b);color:light-dark(#322c26,#f0e9df);border-color:light-dark(#dbcabb,#514137);--color-surface-offset:light-dark(#efe2d3,#43352e);--color-accent:light-dark(#823e33,#f5bd9b)}.split-menu p{font:600 10px ui-monospace,monospace;letter-spacing:.12em;color:light-dark(#7c6d60,#c9a996)}.split-menu a{font-size:14px;font-weight:600}.split-menu a+a{border-top:1px solid light-dark(#dbcabb,#514137)}
@media(max-width:700px){.sp-header>span{display:none}.sp-body{grid-template-columns:1fr}.sp-art{min-height:260px}.sp-sections{grid-template-columns:1fr}.sp-sections section{border-right:0;border-bottom:1px solid var(--color-border)}}
''',
    'ds-131': '''
.showcase:has(.toast-page){max-width:1050px;--color-primary:light-dark(#293f63,#b8d0f0);--color-text:light-dark(#222e40,#e9eff8);--color-bg:light-dark(#f5f4ef,#192332);--color-border:light-dark(#d4d9de,#405068);--color-surface-offset:light-dark(#e7ebec,#2c3c50);--color-accent:light-dark(#a65937,#efb28d)}
.toast-page{width:100%;background:var(--color-bg);color:var(--color-text);border:1px solid var(--color-border);border-radius:18px;overflow:hidden}.tp-header{padding:22px clamp(22px,4vw,48px);display:flex;justify-content:space-between;gap:12px;border-bottom:1px solid var(--color-border)}.tp-header strong{letter-spacing:.09em;font-size:13px}.tp-header strong span{font-weight:400;color:var(--color-text-muted)}.tp-header>span,.tp-kicker,.tp-under,.toast-page footer,.tp-card>span{font:600 11px ui-monospace,monospace;letter-spacing:.1em;color:var(--color-text-muted)}.tp-layout{display:grid;grid-template-columns:1.3fr .7fr;gap:clamp(20px,4vw,65px);align-items:center;padding:clamp(30px,5vw,68px)}.tp-essay h1{font-size:clamp(46px,5vw,70px);line-height:1.02;margin:18px 0 24px}.tp-essay h1 em{color:var(--color-primary);font-weight:normal}.tp-lede{font:normal clamp(19px,2.2vw,25px)/1.4 Georgia,serif;max-width:32ch}.tp-essay>p:not(.tp-lede):not(.tp-kicker):not(.tp-under){max-width:50ch;font-size:14px;color:var(--color-text-muted)}.toast-trigger{background:var(--color-primary);color:var(--color-bg);border:0;border-radius:9px;font-weight:600;margin-top:12px}.toast-trigger span{margin-left:10px}.tp-under{margin:14px 0 0;font-size:10px}.tp-card{background:light-dark(#e5e9ed,#29394c);padding:18px;border-radius:10px;border:1px solid var(--color-border)}.tp-card-art{position:relative;height:200px;background:light-dark(#c3d1d4,#4b6572);overflow:hidden;margin-bottom:22px}.tp-page{position:absolute;width:47%;height:145%;left:28%;top:12%;transform:rotate(-18deg);background:#f5e9d4;box-shadow:14px 10px 20px #263c4a40}.tp-page:after{content:'';position:absolute;top:25%;left:20%;width:58%;height:30%;border-top:2px solid #9eabac;border-bottom:2px solid #9eabac}.tp-pencil{position:absolute;width:8px;height:130%;top:-10%;left:72%;transform:rotate(34deg);background:#aa6143;box-shadow:3px 5px 10px #263c4a55}.tp-card h2{font:normal 28px/1.1 Georgia,serif;margin:10px 0}.tp-card p{font-size:13px;color:var(--color-text-muted);margin:0}.toast-page footer{padding:18px clamp(22px,4vw,48px);border-top:1px solid var(--color-border)}
.auto-toast{background:light-dark(#222e40,#e9eff8);color:light-dark(#fff,#192332);border:1px solid light-dark(#222e40,#e9eff8)}.auto-toast__close:hover{background:light-dark(#3e4c60,#cfdae8)}
@media(max-width:700px){.tp-header>span{display:none}.tp-layout{grid-template-columns:1fr}.tp-card{max-width:340px}.tp-card-art{height:170px}}
''',
}
