"""Pilot 03 contextual scenery for the anchored form and disclosure spells.

The interaction markup and behavior live in README.md. This module adds only
editorial composition; it never manufactures an active state.
"""

HINTS = {
    "ds-48": "Enter an incomplete email, then Tab away. Correct it to watch the browser-owned validation state clear.",
    "ds-49": "Open Filters with the native disclosure. Choose preferences, then activate Filters again to close. Selections are visual only; no results are recalculated.",
    "ds-50": "Tab through the settings. Each field’s guidance follows focus; on a narrow screen it stays in the reading flow.",
}

HTML = {
    "48": '''<main class="invite-scene"><aside aria-label="Workspace summary"><span class="scene-kicker">Northstar studio</span><strong>12 makers.<br>One clear place.</strong><p>Invite a collaborator to the autumn field-notes workspace.</p><div class="avatar-row" aria-hidden="true"><i>AM</i><i>KL</i><i>SR</i><i>+9</i></div></aside><form class="invite-card" action="#invite-preview"><p class="scene-kicker">Workspace invitation / Draft</p><h1>Bring someone in.</h1><p class="intro">We’ll use this address for the invitation. Nothing is sent in this demonstration.</p><div class="field"><label for="invite-email">Work email</label><input id="invite-email" name="email" type="email" autocomplete="email" required aria-describedby="invite-email-note invite-email-error" placeholder="name@company.com"><small id="invite-email-note">Use the address they check at work.</small><p class="error-bubble" id="invite-email-error"><strong>Check the email address</strong><span>Include a name, @ sign and domain—for example, ari@northstar.co.</span></p></div><div class="field"><label for="invite-role">Workspace role</label><select id="invite-role" name="role"><option>Editor — can create and publish</option><option>Reviewer — can comment</option></select></div><button type="submit">Review invitation <span aria-hidden="true">→</span></button></form></main>''',
    "49": '''<main class="catalogue-scene"><header><div><p class="scene-kicker">Atlas supply / Field collection</p><h1>Made for the long way round.</h1></div><p>Trail equipment selected for repairability, honest materials and years of use.</p></header><div class="result-bar"><p><strong>24 pieces</strong><span>Autumn field collection</span></p><details class="filterbar"><summary class="filter-trigger">Filters <span aria-hidden="true">＋</span></summary><form class="filter-panel" action="#filter-selection"><div class="panel-head"><div><span class="scene-kicker">Refine collection</span><strong>What matters to you?</strong></div></div><fieldset><legend>Category</legend><label><input type="checkbox" name="category" value="packs"> Packs <span>8</span></label><label><input type="checkbox" name="category" value="shelter"> Shelter <span>6</span></label><label><input type="checkbox" name="category" value="camp"> Camp goods <span>10</span></label></fieldset><fieldset><legend>Best for</legend><label><input type="radio" name="use" value="any" checked> Any journey</label><label><input type="radio" name="use" value="weekend"> Weekends</label><label><input type="radio" name="use" value="expedition"> Expeditions</label></fieldset><label class="sort">Order <select name="sort"><option>Field notes’ pick</option><option>Price, low to high</option><option>Lightest first</option></select></label><p class="filter-note">Selections are a visual preview; this zero-JS demo does not update the collection.</p><button type="submit">Save selection</button></form></details></div><section class="product-grid" aria-label="Collection preview"><article><span>01 / Carry</span><div aria-hidden="true">△</div><h2>Ridgeline 28L</h2><p>Waxed canvas · Moss</p></article><article><span>02 / Rest</span><div aria-hidden="true">◯</div><h2>Roam blanket</h2><p>Recycled wool · Ochre</p></article><article><span>03 / Light</span><div aria-hidden="true">◇</div><h2>Beacon lamp</h2><p>Aluminium · Ember</p></article></section><p id="filter-selection" class="selection-anchor" tabindex="-1">Your chosen controls remain selected above. Applying them to data requires application logic.</p></main>''',
    "50": '''<main class="settings-scene"><header><p class="scene-kicker">Lumen publishing / Workspace</p><h1>Shape your byline.</h1><p>Set the public details that travel with every story you publish.</p></header><form class="settings-form" action="#settings-preview"><div class="form-row"><div class="control"><label for="public-name">Public name</label><input id="public-name" name="name" autocomplete="name" value="Mara Ellison" aria-describedby="help-name"></div><aside class="help-rail" id="help-name"><span>01</span><strong>Recognisable, not rigid.</strong><p>Use the name readers know. You can include a middle initial or studio name.</p></aside></div><div class="form-row"><div class="control"><label for="profile-url">Profile address</label><div class="url-input"><span aria-hidden="true">lumen.press/</span><input id="profile-url" name="slug" value="mara-ellison" pattern="[a-z0-9-]+" aria-describedby="help-url"></div></div><aside class="help-rail" id="help-url"><span>02</span><strong>Keep it easy to share.</strong><p>Lowercase letters, numbers and hyphens only. Existing story links will keep working.</p></aside></div><div class="form-row"><div class="control"><label for="story-replies">Story replies</label><select id="story-replies" name="replies" aria-describedby="help-replies"><option>People I follow</option><option>All members</option><option>No one</option></select></div><aside class="help-rail" id="help-replies"><span>03</span><strong>You set the boundary.</strong><p>This controls who can start a private response from your published stories.</p></aside></div><button type="submit">Preview profile <span aria-hidden="true">→</span></button><p id="settings-preview" class="form-note">Demonstration only—these settings are not saved.</p></form></main>''',
}

CSS = {
"ds-48": r'''
.invite-scene{display:grid;grid-template-columns:minmax(210px,.72fr) minmax(0,1.28fr);background:light-dark(#193d38,#122924);border-radius:28px;overflow:hidden;box-shadow:0 28px 80px #102b2426}.invite-scene>aside{padding:clamp(28px,5vw,58px);color:#f2ead8;background:linear-gradient(145deg,#214c43,#15352f);display:flex;flex-direction:column;justify-content:flex-end;min-height:560px}.invite-scene>aside strong{font:400 clamp(30px,4vw,48px)/1.06 Georgia,serif;letter-spacing:-.04em;margin:18px 0}.invite-scene>aside p{color:#d0ddd5}.avatar-row{display:flex;margin-top:26px}.avatar-row i{display:grid;place-items:center;width:42px;height:42px;border-radius:50%;background:#e9b96e;color:#183a34;border:3px solid #214c43;font:700 10px ui-monospace;margin-right:-8px}.invite-card{padding:clamp(28px,5vw,62px);background:light-dark(#fffdf7,#17211e)}.invite-card .intro{color:var(--color-text-muted);max-width:45ch}.field{margin-top:24px}.field label{display:block;font-weight:700;margin-bottom:8px}.field input,.field select{width:100%;min-height:52px;border:1px solid var(--color-border);border-radius:10px;background:var(--color-bg);color:inherit;padding:0 14px;font:inherit}.field small{display:block;color:var(--color-text-muted);margin-top:7px}.invite-card button{margin-top:28px;min-height:50px;border:0;border-radius:999px;padding:0 22px;background:#d66c47;color:#fff;font-weight:750}.error-bubble strong,.error-bubble span{display:block}.error-bubble span{font-size:12px;margin-top:2px}@media(max-width:650px){.invite-scene{grid-template-columns:1fr;border-radius:20px}.invite-scene>aside{min-height:210px;padding:24px}.invite-scene>aside strong{font-size:32px}.avatar-row{display:none}.invite-card{padding:26px 22px}}
''',
"ds-49": r'''
.catalogue-scene{width:100%;padding:clamp(22px,5vw,56px);background:light-dark(#f1eee5,#18201d);border:1px solid var(--color-border);border-radius:28px}.catalogue-scene>header{display:flex;align-items:end;justify-content:space-between;gap:30px;padding-bottom:28px}.catalogue-scene>header h1{max-width:12ch}.catalogue-scene>header>p{max-width:34ch;color:var(--color-text-muted)}.result-bar{display:flex;align-items:center;justify-content:space-between;gap:16px;border-block:1px solid var(--color-border);padding:14px 0}.result-bar>p{margin:0;display:grid}.result-bar>p span{font-size:12px;color:var(--color-text-muted)}.filter-trigger{list-style:none;display:flex;align-items:center;gap:18px;min-height:46px;padding:0 18px;border-radius:999px;background:#c75135;color:#fff;font-weight:750;cursor:pointer}.filter-trigger::-webkit-details-marker{display:none}.filterbar[open] .filter-trigger span{rotate:45deg}.filter-panel{padding:22px}.panel-head strong{display:block;font:400 24px Georgia,serif;margin-top:4px}.filter-panel fieldset{border:0;border-top:1px solid var(--color-border);padding:16px 0 4px;margin:16px 0 0}.filter-panel legend,.sort{font-weight:750}.filter-panel fieldset label{display:flex;align-items:center;gap:10px;min-height:38px}.filter-panel fieldset label span{margin-left:auto;color:var(--color-text-muted)}.filter-panel input{accent-color:#c75135}.sort{display:grid;gap:7px;border-top:1px solid var(--color-border);padding-top:16px}.sort select{min-height:44px;border:1px solid var(--color-border);border-radius:8px;padding:0 10px;background:var(--color-bg);color:inherit}.filter-note{font-size:12px;color:var(--color-text-muted);margin:16px 0}.filter-panel button{width:100%;min-height:46px;border:0;border-radius:8px;background:#1f4b43;color:#fff;font-weight:750}.product-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:14px;padding-top:24px}.product-grid article{padding:18px;border-radius:16px;background:light-dark(#fffdf8,#222c28)}.product-grid article>span{font:600 10px ui-monospace;color:var(--color-text-muted)}.product-grid article>div{display:grid;place-items:center;aspect-ratio:1.4;margin:14px 0;background:light-dark(#dce2d5,#303b35);color:#c75135;font-size:54px}.product-grid h2{font:400 21px Georgia,serif;margin:0}.product-grid p,.selection-anchor{font-size:12px;color:var(--color-text-muted);margin:5px 0}.selection-anchor{margin-top:22px}@media(max-width:650px){.catalogue-scene{padding:20px;border-radius:20px}.catalogue-scene>header{display:block}.catalogue-scene>header h1{font-size:38px}.result-bar{align-items:flex-start}.product-grid{grid-template-columns:1fr 1fr}.product-grid article:last-child{display:none}.filterbar{max-width:55%}.filter-trigger{padding:0 13px;gap:10px}.filter-panel{max-width:none}}
''',
"ds-50": r'''
.settings-scene{width:min(100%,840px);padding:clamp(26px,5vw,58px);border-radius:28px;background:light-dark(#f7f2e8,#18211f);box-shadow:0 28px 80px #102b241a}.settings-scene>header{border-bottom:1px solid var(--color-border);margin-bottom:8px}.settings-scene>header p:last-child{color:var(--color-text-muted);max-width:48ch}.settings-form{max-width:520px}.form-row{padding:22px 0;border-bottom:1px solid var(--color-border)}.control label{display:block;font-weight:750;margin-bottom:8px}.control input,.control select{width:100%;min-height:50px;border:1px solid var(--color-border);border-radius:9px;padding:0 13px;background:var(--color-bg);color:inherit;font:inherit}.url-input{display:flex;align-items:center;border:1px solid var(--color-border);border-radius:9px;background:var(--color-bg);overflow:hidden}.url-input span{padding-left:13px;color:var(--color-text-muted);white-space:nowrap}.url-input input{border:0;border-radius:0;padding-left:2px}.help-rail{border-left:3px solid #bd603e;padding:4px 0 4px 14px;background:light-dark(#f7f2e8,#18211f)}.help-rail>span{font:700 10px ui-monospace;color:#bd603e}.help-rail strong{display:block;font-family:Georgia,serif;margin:3px 0}.help-rail p{font-size:12px;color:var(--color-text-muted);margin:0}.settings-form>button{margin-top:24px;min-height:50px;border:0;border-radius:999px;padding:0 22px;background:#224c44;color:#fff;font-weight:750}.form-note{font-size:12px;color:var(--color-text-muted);margin-top:12px}@media(max-width:720px){.settings-scene{padding:25px 20px;border-radius:20px}.settings-form{max-width:none}.form-row{padding:18px 0}.help-rail{margin-top:12px}.url-input span{font-size:13px}}
''',
}
